refnx/refnx

- .gitignore
- refnx/analysis/__init__.py
- refnx/dataset/__init__.py
- refnx/reduce/__init__.py
- refnx/util/__init__.py
This enables testing of submodules of `refnx` within an interpreter, also by the runtests.py script
> MAINT: added test function to __init__.py for each module

- refnx/analysis/curvefitter.py
- refnx/analysis/test/test_curvefitter.py
This is useful for sampling multimodal distributions. With multiple temperatures (specified by ntemp kwd) the higher temperatures have greater freedom to explore less probable regions of the posterior.
> ENH: add parallel tempering for the CurveFitter

- refnx/analysis/curvefitter.py
- refnx/analysis/test/test_curvefitter.py
Whilst `emcee.EnsembleSampler` does have an `acor` property I wanted to be able to see the autocorrelation function. This PR adds that function via an `acf` method. An autocorrelation function is obtained for each varying parameter. The autocorrelation function can be used to figure out how much to thin the chain.
> ENH: added an autocorrelation estimation function

- refnx/reflect/structure.py
- refnx/reflect/test/test_reflect.py
add `reversed` attribute to `refnx.reflect.Structure`. This enables you to calculate the front/back reflectivity from the same structure very easily.
> ENH: reversed structure

- refnx/analysis/objective.py
- setup.py
burn/thin in `objective.pgen`. THIs can already be achieved by chain processing in curvefitter, but this offers another way to do it.
> MAINT: burn/thin pgen

- refnx/analysis/curvefitter.py
- refnx/analysis/test/test_curvefitter.py
- refnx/reflect/test/test_reflect.py
THin during sampling. This reduces the memory footprint significantly, which is an issue for large chain sizes.
This PR also removes the nburn kwd. One can always use process_chain to do any further burning and thinning.
> MAINT: thin during sampling (otherwise memory can explode)

- refnx/reflect/structure.py
structure.py cannot be imported into recent Python 2 as it uses non-ASCII characters but does not declare an encoding.
```
E     File .../refnx/reflect/structure.py", line 357                                                            
E   SyntaxError: Non-ASCII character '\xc2' in file .../refnx/reflect/structure.py on line 358, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details                   
```
(Initial assumption was that this was an Å from the thicknesses in L357 hence setting the encoding; it actually just a non-breaking space in "20 A", so perhaps fixing the file to be ASCII is better in this case)
> BUG: encoding not specified on source code

- refnx/reduce/batchreduction.py
- refnx/reduce/test/test_batch_reduce.py
Code to extract runs based on run numbers was collecting only the indexes in the cache not the actual data.
> BUG: fix run number selection from cache

- refnx/reduce/platypusnexus.py
For some runs, setting the tolerance on the auto beamfinder is required so that the finder converges as it moves across the y-t image. The default 1% convergence criterion might not be met by the right part of the image, resulting in a 30-60px beam width; relaxing convergence to 2 or 3% allows a 2-3px beam width to be determined with 2 or 3 iterations before convergence.
> Allow beam finder tolerance to be varied

- refnx/analysis/curvefitter.py
- refnx/analysis/test/test_curvefitter.py
Loading a large emcee chain causes a *large* amount of memory to be used during np.loadtxt. Here the loading is optimized for memory footprint.
> ENH: memory optimized load_chain

- refnx/analysis/objective.py
The `GlobalObjective.lnprior` was including `Objective.model.lnprior` when `Objective.lnprior` was already including it. Thus the model prior was being counted twice. This bug was observed when `Objective.model.lnprior` was being called with impossible values - `Objective.lnprior` is supposed to shortcut to return `-np.inf` if any of the parameters are impossible.
> BUG: global_objective.lnprior model prior overcount

- refnx/_lib/test/test_util.py
- refnx/analysis/curvefitter.py
- refnx/analysis/parameter.py
- refnx/dataset/data1d.py
- refnx/reduce/event.py
- refnx/reduce/platypusnexus.py
- refnx/reduce/test/test_event.py
- refnx/reduce/test/test_reduce.py
Kinetic data reduction currently works by dividing the event list into contiguous time slices, 
Future experiments may use different groupings of the event list. FOr example, they may want to have the grouping:
[[0, 2, 4, 6], [1, 3, 5, 7]] instead of [[0, 1, 2, 3], [4, 5, 6, 7]].
This PR allows the user to provide a function that will group the event list into whatever the user sees fit. The function is expected to return an (N, T, Y, X) detector image, as well as a frame_count array (N, ) which specifies the total number of frames that went into making each of the detector images.
The frame count is used to determine the fraction of beam monitor counts used for normalising the dataset.
> Eventfilter - providing a function to create detector image from eventlist

- refnx/reduce/batchreduction.py
pd.read_excel deprecated the parse_cols kwd. It's now usecols.
> MAINT: batchreduction - pd.read_excel parse_cols dep

- doc/conf.py
- refnx/analysis/curvefitter.py
- refnx/analysis/model.py
- refnx/analysis/objective.py
- refnx/analysis/parameter.py
- refnx/analysis/test/test_globalfitting.py
- refnx/analysis/test/test_objective.py
- refnx/dataset/data1d.py
- refnx/reduce/bounded_splines.py
- refnx/reduce/peak_utils.py
- refnx/reduce/platypusnexus.py
- refnx/reflect/reflect_model.py
- refnx/reflect/structure.py
The log-prior consists of the varying parameter log-probabilities, the model log-probability (which shouldn't include any parameter log-probs).
The log-likelihood consists of the model vs data log-probability.
However, there may be an extra term which is difficult for the user to add via any of the above.
For example, the user may not be able to amend the model code. This PR adds the option of providing a `lnprob_extra` function which is folder into the log-prior term.
> ENH: add lnprob_extra function

- setup.py
Installation without cython is possible but should be warned against.
> Warn about missing cython at install time

- refnx/reduce/batchreduction.py
- refnx/reduce/test/test_batch_reduce.py
Improve documentation and usability of batch reducer, including:
*    adding an on-disk cache of reduced data so that the reducer can be restarted and plots can be made without requiring all data to be rereduced.
*    making the list of reduced runs prettier by setting column types to `int` where appropriate and replacing `NaN` with blank entries.
(#99 can't be reopened so recreating)
>  Batch reducer improvements

- refnx/analysis/parameter.py
- refnx/analysis/test/test_parameter.py
Use rv to set bounds.
e.g.
```
x.setp(bound=norm(0, 1))
```
> ENH: use rv to set bounds

- examples/analytical_profiles/brushes/brush.py
Monotonicity penalty now takes into account vf of the left_slabs passed to the brush object.
> Improved monotonicity penalty

- examples/analytical_profiles/brushes/brush.py
- refnx/reflect/spline.py
- refnx/reflect/structure.py
- refnx/reflect/test/test_spline.py
- refnx/reflect/test/test_structure.py
@arm61 @llimeht @igresh @llimeht 
This is a change that significantly alters behaviour. When a `Structure` is created one used to be able to use `fronting` or `backing` to define how you wanted to solvate the structure. 
Now the string arguments have been removed, and you have to supply an `SLD` instance.
If you don't supply an SLD instance then the SLD of the backing medium is used by default (`Structure[-1].slabs[-1]`).
This should be back compatible for those that automatically use backing medium for solvation, but those who use fronting medium for solvation need to supply an `SLD` instance.
The PR has the advantage that an arbitrary SLD can be used for solvation, it doesn't have to be the fronting or backing media.
> ENH: solvation now done by specific solvent

- refnx/reflect/reflect_model.py
- refnx/reflect/test/test_reflect.py
Adds the ability to add create a mixed area reflectivity model.
For example, you may have a surface that is 50% covered by a monolayer, and 50% of a surface that isn't. You can create a `Structure` for each of those areas, and combine them together in a `MixedReflectModel`, with a scale factor for each of the two structures. THe scale factors are used to calculate the relative contribution of each area.
> ENH: mixed_model

- refnx/reduce/platypusnexus.py
- refnx/reduce/reduce.py
- refnx/reduce/test/test_platypusnexus.py
catalogue keyword changed from `path` to `data_folder` for consistency.
`PlatypusReduce.reduce` now returns a list of datasets, as well as the original dict that was returned.
> MAINT: catalogue kwd change

- refnx/analysis/objective.py
- refnx/analysis/test/test_curvefitter.py
- refnx/analysis/test/test_objective.py
- refnx/reflect/test/test_reflect.py
This PR fixes a bug in which the covariance matrix calculated by `objective.covar` was wrong.
The leading diagonal was correct, but the off diagonal elements were rescaled incorrectly.
A test is added to check the covariance matrix against `scipy.optimize.least_squares`.
> BUG: fix covariance calculation

- refnx/analysis/objective.py
- refnx/analysis/test/NISTModels.py
- refnx/analysis/test/test_objective.py
These changes identify which parameters are singular when asking for `objective.covar`.
> ENH: covar tells you which parameters are singular

- refnx/reduce/batchreduction.py
The syntax for selecting columns varies across pandas releases; this seems to work with all pandas >= 0.20 thus saving a versioned dependency on a difficult-to-build package.
> Fix column handling for pandas compatibility

- refnx/analysis/parameter.py
- refnx/analysis/test/test_parameter.py
All `Parameter` instances were sharing the same `Interval` instance, a reasonably bad bug.
> BUG: all Parameter instances were sharing same Interval instance

- examples/interactive_fitter/interactive_modeller.py
- examples/interactive_fitter/interactive_reflectometry_modeller.ipynb
This PR adds some initial code for a Jupyter notebook based reflectometry fitter. It only does slabs at the moment, because slabs are the easiest to create a GUI for. The functionality is basic, in that restricted Q range fitting, etc, isn't developed yet. However, in it's current form it can be used to analyse data.
The app is used to set up a model, which can then be fitted within the gui, or developed further with code/object interactions in other notebook cells.
> ENH: interactive modeller

- refnx/reflect/test/test_reflect.py
- src/refcalc.cpp
The C-plugin was taking the absolute value of the background and adding it to the theoretical reflectivity. The Python equivalent was not taking the absolute value. This PR makes the C-plugin equivalent to the Python version. Those who wish to enforce a background greater than 0 can use a parameter bound.
> MAINT: allow negative background to be added

- examples/mpi_parallelisation.py
- refnx/_lib/__init__.py
- refnx/_lib/test/test_util.py
- refnx/_lib/util.py
- refnx/analysis/curvefitter.py
Change to using a `PoolWrapper` class.
Backward incompatibility: change the default of `pool`  in the sampler. -1 now means all CPU's.
> MAINT: change pool organisation

- INSTALL_CONTRIBUTE.md
- azure-pipelines.yml
- setup.py
The `uncertainties` package is only required for testing, not for operation.
> TST: remove uncertainties as a dependency

- CHANGELOG.txt
- refnx/reflect/_interactive_modeller.py
Adds save/load model buttons to the interactive modeller GUI. This modification is based on user experience - when the notebook is saved/loaded then the GUI doesn't maintain widget information (unless widget state is saved). This PR adds buttons that make it easier to (de)serialise models.
> ENH: interactive modeller save/load buttons

- doc/installation.rst
- setup.py
It's only needed for reduction, and it's noted in setup.py in the extras_require section.
> MAINT: remove pandas as a mandatory dependency

- setup.py
set mmacosx-version-min for macOS. This fixes some issues with header files not being found, e.g. https://github.com/pandas-dev/pandas/issues/23424
> BLD: mmacosx-version-min=10.9

- refnx/reflect/_app/treeview_gui_model.py
- refnx/reflect/_app/view.py
- refnx/reflect/_code_fragment.py
- refnx/reflect/reflect_model.py
- refnx/reflect/test/test_reflect.py
Adds the ability to form a mixed area model (based on MixedReflectModel) in the pyqt gui. When the user right clicks on a dataset they can add a structure to the model. The overall reflectivity is a scale factor weighted average of the different structures.
> ENH: adding MixedReflectModel to pyqt gui

- refnx/analysis/objective.py
- refnx/analysis/parameter.py
- refnx/analysis/test/test_curvefitter.py
- refnx/reflect/_code_fragment.py
- refnx/reflect/structure.py
This PR adds the `Structure.plot` method (matplotlib required to use it), to allow one to plot sld profiles for a given structure. If the Structural parameters have associated MCMC chains then it is possible to plot samples from those as well.
The code script generator (in the GUI) has been updated to enable the scripts to produce graphs of the MCMC sampling process. Graphs for the sld profiles and data/fits will be produced when the script is run.
The `Parameters` class is given a pgen method to allow it to yield samples from the chains contained in its varying parameters.
> ENH: easy structure plot

- CHANGELOG.txt
- examples/analytical_profiles/brushes/brush.py
- refnx/analysis/test/test_globalfitting.py
- refnx/reflect/_code_fragment.py
- refnx/reflect/_lipid.py
- refnx/reflect/reflect_model.py
- refnx/reflect/spline.py
- refnx/reflect/structure.py
- refnx/reflect/test/test__lipid.py
- refnx/reflect/test/test_reflect.py
- refnx/reflect/test/test_spline.py
- refnx/reflect/test/test_structure.py
This is a big changeset, and introduces a backwards incompatible change. The `Component.slabs` and `Structure.slabs` properties have been changed to methods, which take an optional `structure` kwd. The reason for this change is so that each `Component` knows what kind of structure it resides in. This is not important for standalone `Component`s, but if a `Component` depends on what's to its left or right, then it's vital.
> MAINT: slabs property --> slabs method

- refnx/reflect/_app/treeview_gui_model.py
- refnx/reflect/_app/ui/motofit.ui
- refnx/reflect/_app/view.py
Allows one to drag and drop Components in a Structure. Within a Structure this has the effect of reordering Components. When moving to another Structure the component is copied to the new structure.
> ENH: drag and drop Components in pyqt GUI

- refnx/reflect/_app/treeview_gui_model.py
- refnx/reflect/_app/ui/motofit.ui
- refnx/reflect/_app/view.py
This PR adds a filter to the refnx GUI so that the user can choose to display only the parameters/datasets being fitted. This makes it easier to distinguish the fitted parameters from the non-fitted parameters.
> ENH: only show pars/data being fitted

- CHANGELOG.txt
- refnx/analysis/parameter.py
- refnx/analysis/test/test_parameter.py
- refnx/reflect/_app/treeview_gui_model.py
- refnx/reflect/_app/view.py
If parameters are linked across datasets then the parameters all update in the tree model. However, only the dataset containing the master parameter would have its reflectivity recalculated.
This PR makes sure that the datasets containing the constrained parameters also get updated.
> Auto update constrained parameters in refnx GUI

- refnx/analysis/curvefitter.py
- refnx/analysis/objective.py
- refnx/analysis/test/test_curvefitter.py
- refnx/analysis/test/test_objective.py
Building on @arm61 work, this PR approximates box bounds for a parameter whose prior is specified by a `PDF` object. These are typically statistical distributions - estimate lower and upper bounds for those as `PDF.rv.ppf([0.005, 0.995])`, which covers 99% of the distribution.
> ENH: approximate box bounds for PDF

- CHANGELOG.txt
- refnx/analysis/__init__.py
- refnx/analysis/curvefitter.py
- refnx/analysis/test/test_curvefitter.py
- refnx/reflect/_code_fragment.py
Adds `autocorrelation_chain` and `integrated_time` to the `refnx.analysis` module. These are used to calculate the autocorrelation function and autocorrelation time of the sampled chain.
> ENH: static autocorrelation_chain function

- CHANGELOG.txt
- refnx/reflect/_app/view.py
When the GUI saves a model it should pickle a ReflectModel. It wasn't  doing this, it was pickling a DataObject. This has now been fixed, but the fix affects back compatibility.
> BUG: make sure that gui save model pickles a ReflectModel

- refnx/reflect/_app/datastore.py
If a dataset was already loaded, then loading it again caused a crash. This was because the model associated with the dataset was wiped.
> BUG: load already loaded dataset

- refnx/reflect/_app/view.py
When extra attributes are added to classes it's likely this will cause the refnx gui to be unable to load experiments saved in a previous version of refnx, because those attributes won't be present when objects are unpickled. It's possible to jump through hoops to try to prevent this (by controlling unpickling), but it makes classes ugly.
In the meantime produce an informative message that tells the user to go back to a previous version of refnx to start with.
> MAINT: give informative message when experiment load fails

- .travis.yml
- doc/conf.py
- doc/environment.yml
- refnx/reflect/_app/view.py
v0.1.8 will add the interfaces attribute to all Components. However, the attribute will be missing in mtft experiment files saved with previous versions. When those experiments are loaded a crash will result because the unpickled Components won't have the attribute. This PR adds the attribute to all the loaded Components if the object doesn't already possess it.
> MAINT: make gui more resistant to missing attributes when loading experiment file

- CHANGELOG.txt
- refnx/reduce/manual_beam_finder.py
If the user specified regions in ManualBeamFinder that lay outside the size of the detector image then crashes could occur.
> MAINT: fix potential crashes in reduction

- CHANGELOG.txt
- setup.py
- src/refcalc.cpp
Reflectivity calculation in refcalc.cpp is much cleaner when using c++11 std::thread compared to a mix of pthreads and windows threading.
> MAINT: use C++11 std::thread for _creflect

- doc/installation.rst
A user reports that they couldn't start the refnx gui with the suggested way of setting up the conda environment (in the installation instructions documentation).
This PR adds a few packages to the suggested setup that will allow the refnx gui to start from the command line. These packages are not required if the GUI isn't being used, but it probably makes sense to have them there. @joscooper
> DOC: expand dependency list

- CHANGELOG.txt
- refnx/reflect/structure.py
Useful when plotting lots of MCMC samples at the same time.
> ENH: align SLD plots at a specific interface

- .travis.yml
- CHANGELOG.txt
- refnx/reflect/__init__.py
- refnx/reflect/structure.py
- refnx/reflect/test/test_structure.py
- src/_cevent.pyx
Create a scattering object using a chemical formula and mass density:
```
sio2 = MaterialSLD('SiO2', density=2.2)
```
`MaterialSLD` extends SLD, so *should* be able to be used in most places where an `SLD` is used.
> ENH: add MaterialSLD object

- .travis.yml
This PR amends the travis tests to create an sdist, install from that sdist, then run the tests. This modification should catch issues like #381.
> TST: travis test from sdist fixes #381

- CHANGELOG.txt
- refnx/analysis/parameter.py
- refnx/analysis/test/test_parameter.py
- refnx/reflect/structure.py
possibly_create_parameter accepts default bounds/vary/constraint. This fixes a bug in MixedSlab.
> MAINT: defaults in possibly_create_parameter

- refnx/reflect/reflect_model.py
the linspace calculations in reflect_model.py can be cached, which will provide a ~5% speedup in constant dq/q reflectivity calculation for some models with a few layers.
> ENH: cache linspace

- CHANGELOG.txt
- refnx/reflect/__init__.py
- refnx/reflect/reflect_model.py
- refnx/reflect/test/test_reflect.py
- reflect.choose_dq_type for finding out fastest mode of resolution smearing.
- User can now select resolution smearing approach in ReflectModel. Choosing
between 'pointwise' or 'constant'.
> ENH: choose fastest smearing type

- CHANGELOG.txt
- refnx/analysis/bounds.py
- refnx/analysis/test/test_bounds.py
@igresh, big performance increase when sampling from this (depending on system).
Fast pickling/unpickling speed is essential for good `multiprocessing` performance. We want all the processor time spent in calculating reflectivities, not being used in pickling overhead. This PR significantly reduces the pickling overhead.
For the system I examined (2 slabs, 3 contrasts, 100 data points per contrast) I went from ~2.3 minutes down to 1.5 minutes for a certain sampling.
The improvement will be less for systems that spend longer calculating reflectivities (such as brushes)
> ENH: speed up (un)pickling of Bounds

- .github/workflows/pythonpackage.yml
- CHANGELOG.txt
- refnx/reflect/_reflect.py
- refnx/reflect/abeles_pyopencl.cl
- refnx/reflect/reflect_model.py
- refnx/reflect/test/test_reflect.py
This PR introduces the use of openCL to calculate the reflectivity. It's not as accurate, or as fast, as the C implementation (and is therefore not preferred). I'm putting it in the source code for completeness, it may come in handy in the future.
It is not used by default.
> MAINT: enable pyopencl for reflectivity calculation

- CHANGELOG.txt
- misc/app/README
- misc/app/motofit.spec
- setup.py
- src/refcalc.c
Looks like there is going to be a quick bug fix release. The Linux wheels are wrong because there isn't a CMPLX macro installed, so the tests don't run.
> BUG: bugfixes

- CHANGELOG.txt
- benchmarks/asv.conf.json
- refnx/reflect/test/test_reflect.py
- setup.py
- src/_creflect.pyx
Try out `-ffast-math` optimisation, which speeds up reflectivity calculation. The main point of concern would be no signed zeros for complex maths arithmetic.
> ENH: -ffast-math optimisation

- CHANGELOG.txt
- refnx/analysis/objective.py
- refnx/analysis/test/test_objective.py
BREAKING CHANGE: move `logp_extra` and `Objective.model.logp` from `Objective.logp` to `Objective.logl`. This is so the prior can be used more easily for pymc3 and dynesty.
> MAINT: logp_extra from logp to logl

- CHANGELOG.txt
- refnx/analysis/objective.py
- refnx/analysis/parameter.py
- refnx/analysis/test/test_curvefitter.py
Not sure if this is going to create problems into the future by removing the float cast in the `Parameter.value` setter. However, from testing it does seem to remove some roadblocks when calculating a gradient with JAX.
```
class Line(Model):
def __init__(self, parameters):
self._parameters = parameters
def model(self, x, p=None, x_err=None):
if p is not None:
self._parameters = p
a, b = self._parameters
return a.value + x * b.value
def g(objective):
obj = objective
v = np.array(obj.parameters)
jacobian = jit(grad(obj.nll))
obj.parameters.pvals = v
def jac(p):
v = np.array(p)
gg = jacobian(v)
obj.parameters.pvals = v
return gg
return jac
```
At the moment it's necessary to create the wrapper for the JAX calculator because the jitted grad function leaves some kind of tracing JAX object in …
> MAINT: remove some roadblocks to JAXification

- refnx/analysis/objective.py
Added a `RuntimeError` to `Transform` for non-finite transformed values when using the logY transform. This should address issue #522.
> Added runtime error to Transform in objective.py

- refnx/analysis/objective.py
Downgrade a RuntimeError to RuntimeWarning. This is because the GUI app would have to jump through too many hoops to filter negative values for logY transform.
> MAINT: check transform for non-finite'

- refnx/reduce/__init__.py
- refnx/reduce/platypusnexus.py
- refnx/reduce/test/test_platypusnexus.py
Adding classes for SpinChannel and SpinSet. 
SpinChannel is an Enum class specifying the spin state in a PlatypusNexus file/
SpinSet is a set of up to 4 spin channels that are kept together for polarisation efficiency correction as well as for use in a future PolarisedReduce class for reducing multiple spin-polarised datasets.
> Spinset classes

- CHANGELOG.txt
- refnx/analysis/objective.py
- refnx/analysis/test/test_model.py
- refnx/analysis/test/test_objective.py
- refnx/dataset/data1d.py
- refnx/dataset/test/test_reflectdataset.py
When fitting something like ellipsometry data the datasets have four values associated with each datapoint, rather than an x/y pair. Viz: the independent variables are `wavelength` and `AOI`, with the dependent variables being `xsi` and `delta`.
The existing refnx analysis code should be already able to handle this in the `Data1D/Model/Objective` framework, so long as the user writes fitfuncs/creates datasets that are consistent with each other.
This PR adds tests to ensure that the analysis code handles this kind of situation correctly. i.e. that a Data1D can have a `y` attribute of shape `(N, M)` and an `x` attribute of shape `(P, Q)`; that a call of Model(x) gives an array of shape `(N, M)`, and that the `Objective` statistics (generative, chisqr, logpost, residuals) are calculated …
> Test that multidimensional data can work

- refnx/reduce/platypusnexus.py
- refnx/reduce/reduce.py
- refnx/reduce/test/test_platypusnexus.py
- refnx/reduce/test/test_reduce.py
SpinSets should be constructed with a fully qualified filename. This removes the data_folder keyword argument.
> Remove `data_folder` kwd from `SpinSet` initialisation

- refnx/reduce/platypusnexus.py
- refnx/reduce/reduce.py
- refnx/reduce/test/test_platypusnexus.py
Improves spin_state detection. If the mode is `POL` then don't look at the analyser to specify the spin state.
Also changes the way the currents are examined. It's not a good idea to check if a current is equal to zero because equality checks for floating point values are a bad idea TM. Thus to check if a flipper is on or off make examine if the current is less than 0.1 A (OFF) or greater (ON). It might be preferable to check for `pn.cat.pol_flip_status` or `pn.cat.anal_flip_status` instead of current.
> MAINT: improve spin_state detection

- refnx/reflect/test/test_reflect.py
Don't want people thinking that the fast reflectivity backend isn't available (when it is) because of a warning emitted during testing.
> MAINT: filter slow reflectivity warning

- setup.py
Cutting a new release so that universal macOS wheels are available, and so that wheels can be built with oldest supported numpy, which means that the wheel doesn't require the latest numpy be installed.
> REL: v0.1.24

- refnx/reduce/batchreduction.py
A change to pandas (at some stage) broke the summary feature of the batch reduction cache. Going via a list lets it work once more.
> MAINT: Fix generating pandas summary from batch reducer

- CHANGELOG.txt
- refnx/reduce/reduce.py
- refnx/reduce/test/test_reduce.py
We revised the `ReflectReduce.write_offspecular`  to output an ascii file with four columns, qz,qx,m_ref, m_ref_err.
> MAINT: write_offspec in 4 column ascii

- refnx/reduce/platypusnexus.py
Minor error when plotting caused by escape character "\\" in the ax.set_ylabel(r"$Q_z (\\AA^{-1})$"), in Jupyter notebook. 
Jupyter NB returned was " ParseException: Expected end of text, found '$'  (at char 0), (line:1, col:1)"
Remedied by replacing "\\" with "\"
> BUG: Fix plot os label

- CHANGELOG.txt
- refnx/reflect/test/test_reflect.py
@llimeht this might work? The maximum rtol difference that I could see in the Debian build log was 2.01e-12. I've relaxed it to  1e-9, which should be more than enough.
I also noticed that there were a lot of warnings building the documentation. A good place to help out would be to investigate whether it's Debian emitting those warnings, or if refnx can improve it's doc building at all. TBH restructured text gives me nightmares. I wish I could do everything in markdown. I think sphinx can do that, but it'd be a bother to transfer to MD.
> TST: relax rtol on kernel comparison

- src/_cevent.pyx
Fix event data processing on big-endian architechtures: The event-mode files in the data bundle for the tests are always little-endian as they are generated on the insturment machines. Opening the files needs to be specific about the byte-order and not open with an implicitly native byte-order as np.frombuffer normally does.
Test failure observed on the Debian s390x CI workers. 
https://ci.debian.net/packages/r/refnx/testing/s390x/
```
reduce/test/test_platypusnexus.py::TestPlatypusNexus::test_event FAILED  [ 45%]
reduce/test/test_platypusnexus.py::TestPlatypusNexus::test_event_folder FAILED [ 45%]
reduce/test/test_platypusnexus.py::TestPlatypusNexus::test_reduction_runs FAILED [ 46%]
reduce/test/test_reduce.py::TestPlatypusReduce::test_event_reduction FAILED [ 55%]
E   AssertionError …
```
> [BUG] Force event-mode logs to be read as LE int32
