refnx/refnx

.travis.yml, examples/experiment.mtft, examples/referenceAnalysisScript.py, examples/test.py, examples/test2.py, motofit/UDF_GUImodel.py, motofit/View.py, motofit/dataobject.py, motofit/paramsstore_GUImodel.py, motofit/reflectivity_parameters_GUImodel.py, refnx/analysis/__init__.py, refnx/analysis/curvefitter.py, refnx/analysis/reflect.py, refnx/analysis/test/test_curvefitter.py, refnx/analysis/test/test_globalfitting.py, refnx/analysis/test/test_reflect.py
Split out `CurveFitter` into `CurveFitter` and `FitFunction` classes. This is to make multiprocessing possible for `emcee`.
=> Multiprocessing refactor

.gitattributes, .gitignore, refnx/reduce/batchreduction.py, refnx/reduce/test/test_batch_reduce.py
* IPython as an optional dependency
* Doc improvements
* More tests
* gitignore and gitattributes improvements
=> Batch reduction improvements

refnx/analysis/test/test_reflect.py, refnx/reduce/batchreduction.py, refnx/reduce/test/test_batch_reduce.py, refnx/reduce/test/test_platypusnexus.py
Adding @llimeht batch reduction code
=> Batch reduce

refnx/reduce/event.py, refnx/reduce/test/test_event.py, setup.py, src/_cevent.pyx
Made a cython event mode reader which speeds up eventmode reading by a factor of 5.
=> ENH: cython event reader in reduction

motofit/View.py, motofit/dataobject.py, refnx/dataset/data1d.py, refnx/dataset/reflectdataset.py
=> MAINT: refactored Data1D.y_sd to y_err

refnx/analysis/curvefitter.py, refnx/analysis/reflect.py, refnx/analysis/test/test_reflect.py
Subclass AnalyticReflectivityFunction
=> Adding a mechanism for analytical reflectivity profiles

.travis.yml, appveyor.yml, refnx/analysis/test/test_reflect.py
Make sure the _creflect module is tested
=> TST: make sure the _creflect module is tested

refnx/analysis/_reflect.py, src/_creflect.pyx, src/refcalc.cpp
Speedup for pure python calculation is markedly improved though!
=> MAINT: minor speedups for reflectivity calculation

refnx/reduce/peak_utils.py, slim/manual_beam_finder.py, slim/ui/manual_beam.ui, slim/view.py
Create a manual beam finder for locating a specular beam
=> ENH:Manual beam finder

refnx/reduce/platypusnexus.py, refnx/reduce/reduce.py, refnx/util/general.py, refnx/util/test/test_general.py, slim/model.py, slim/view.py
cache direct beam processing for faster reduction
=> ENH: cache direct beam processing for faster reduction

refnx/analysis/test/test_curvefitter.py, refnx/reflect/_reflect.py, refnx/reflect/reflect_model.py, refnx/reflect/structure.py, refnx/reflect/test/test_reflect.py, src/_creflect.pyx, src/refcalc.cpp, src/refcalc.h
Instead of using the workers keyword change it to threads, because that's what emcee uses.
=> change worker kwd to threads to tally with emcee

refnx/analysis/bounds.py, refnx/analysis/test/test_bounds.py
In a semi-closed Interval, such as `[-np.inf, 5]`, then a value was being made valid via clipping to the relevant limit. Now they are made valid by reflecting from the limit. In the example just given a value of 6.5 would be made valid by converting it to 5 - (6.5 - 5) = 3.5.
=> ENH: semi-closed Interval - valid via reflection

refnx/reduce/reduce.py
(probably an interim change to the API to be eventually replaced by some sort of ReducerOptions configuration)
=> Make bg subtraction configurable per angle

examples/CurveFitter_EMCEE.ipynb, examples/reflectometry_analysis.ipynb, refnx/analysis/__init__.py, refnx/analysis/curvefitter.py, refnx/analysis/test/test_curvefitter.py
Moved `process_chain` and `load_chain` to their own functions. This makes it simpler to load and process chains.
=> MAINT: moved process_chain to function

refnx/_lib/util.py, refnx/analysis/curvefitter.py, refnx/analysis/model.py, refnx/analysis/test/test_curvefitter.py
- Deals with new/old emcee thinning behaviour
- Can use the new tqdm w new emcee if it's installed.
=> MAINT: deal with new/old emcee w thinning

refnx/analysis/objective.py, refnx/analysis/test/test_curvefitter.py, refnx/analysis/test/test_objective.py
BUG: unweighted residuals werent calculated correctly
=> TST: check unweighted residual calcn

refnx/analysis/test/test_curvefitter.py, refnx/analysis/test/test_globalfitting.py, refnx/reduce/test/test_event.py, refnx/reflect/test/test_reflect.py
The test suite is timing out on conda-forge/appveyor. These are inital attempts to reduce the computational resources for the test suite.
=> TST: try to reduce test resources.

refnx/dataset/data1d.py, refnx/dataset/test/test_reflectdataset.py
For Monte Carlo resampling purposes
=> ENH: resynthesise datasets

examples/analytical_profiles/brushes/brush.py, refnx/reflect/structure.py
That uses gamma as a parameter, and adjusts spline extent to make adsorbed amount correct.
=> New and improved brush

refnx/reduce/platypusnexus.py, refnx/reduce/reduce.py, refnx/reduce/test/test_reduce.py
Groundwork for Spatz reduction.
=> ENH: groundwork for Spatz reduction

refnx/analysis/objective.py
=> MAINT: add an objective name

refnx/reduce/platypusnexus.py, refnx/reduce/test/test_platypusnexus.py
check that foreground is totally within detector and that background pixels are totally within detector
=> MAINT: check that foreground is totally within detector

refnx/analysis/objective.py, refnx/analysis/test/test_curvefitter.py
Remove `use_weights` attribute from `Objective`.
=> MAINT: objective.use_weights attribute removed

refnx/reflect/reflect_model.py, refnx/reflect/test/test_reflect.py
Calculation of reflectivity signal from a full resolution kernel was not being tested, this PR adds the test. I took the opportunity to change the specification of the resolution kernel array. Whilst this is not back compatible I don't think this will cause any issues, because AFAICT few facilities bother with that.
=> MAINT: fix and add test for full resolution kernel

refnx/reduce/platypusnexus.py, refnx/reduce/reduce.py
Gravity based TOF corrections for Platypus
=> MAINT: toff gravity

.travis.yml, appveyor.yml, refnx/analysis/objective.py, refnx/analysis/test/test_curvefitter.py
A helper method to create a corner plot for the chains associated with each varying parameter in an objective.
=> ENH: add corner method

examples/analytical_profiles/surf_mono/dppc_water_xrr.ipynb, refnx/reflect/__init__.py, refnx/reflect/_lipid.py
Put the lipid Component into the main package
=> MAINT refactored lipid

refnx/reflect/_lipid.py, refnx/reflect/structure.py, refnx/reflect/test/test__lipid.py
Supercedes #155. You can solvate the lipid tail and head groups with different solvents. This PR also adds tests for LipidLeaflet.
=>  ENH: solvate head/tails of lipid separately.

.travis.yml, INSTALL_CONTRIBUTE.md, appveyor.yml, refnx/analysis/objective.py, refnx/analysis/test/test_bounds.py, refnx/analysis/test/test_objective.py, refnx/reflect/reflect_model.py, setup.py
- The log-likelihood has been updated to include the 2pi term.
- pymc3 functionality has been improved and tests added
- loglikelihood tested against pymc3 for same fitting system
- parameter --> pymc3 distribution updated and tested
=> MAINT: update log-likelihood and develop pymc3 functionality

refnx/analysis/curvefitter.py
Wrappers for the objective evaluators were originally added to aid pickling. These are not needed any more because emcee does the pickling.
=> MAINT: remove objective wrapper'

refnx/analysis/parameter.py, refnx/analysis/test/test_parameter.py, refnx/dataset/data1d.py, refnx/dataset/reflectdataset.py, refnx/reflect/_code_fragment.py, refnx/reflect/test/test__code_fragment.py
- Generator for building a code fragment from an Objective (using repr)
- A constraint tree parser for rebuilding a constraint (with the eventual hope of generating code fragments for linked parameters)
=> ENH: constraint tree parser and a code fragment generator

appveyor.yml, azure-pipelines.yml, refnx/analysis/bounds.py, refnx/analysis/curvefitter.py, refnx/analysis/model.py, refnx/analysis/objective.py, refnx/analysis/parameter.py, refnx/analysis/test/test_objective.py, refnx/analysis/test/test_parameter.py, refnx/dataset/data1d.py, refnx/dataset/reflectdataset.py, refnx/reflect/_app/ui/motofit.ui, refnx/reflect/_app/view.py, refnx/reflect/_code_fragment.py, refnx/reflect/reflect_model.py, refnx/reflect/structure.py, refnx/reflect/test/test__code_fragment.py, refnx/reflect/test/test_structure.py, setup.py
Also bumps minimum Python because of f-strings.
=> ENH: code fragment generator

appveyor.yml, azure-pipelines.yml, refnx/analysis/bounds.py, refnx/analysis/curvefitter.py, refnx/analysis/model.py, refnx/analysis/objective.py, refnx/analysis/parameter.py, refnx/dataset/data1d.py, refnx/dataset/reflectdataset.py, refnx/reflect/_code_fragment.py, refnx/reflect/reflect_model.py, refnx/reflect/structure.py, refnx/reflect/test/test__code_fragment.py, setup.py
Probably too soon to leave 3.5 behind
=> Roll back f-string

CHANGELOG.txt, refnx/dataset/data1d.py, refnx/dataset/test/test_reflectdataset.py, refnx/reflect/_app/dataobject.py, refnx/reflect/_app/treeview_gui_model.py, refnx/reflect/_app/ui/lipid_leaflet.ui, refnx/reflect/_app/view.py, refnx/reflect/reflect_model.py, refnx/reflect/structure.py, refnx/reflect/test/test_reflect.py
See title. Also, amended GUi to allow constant dq/q
=> BUG: ReflectModel default was single threaded instead of multithreaded

CHANGELOG.txt, refnx/_lib/util.py, refnx/reflect/_app/view.py
Parallelise the fitting process, if `scipy.optimize.differential_evolution` is used.
=> ENH: parallelise the fitting

refnx/analysis/curvefitter.py, refnx/analysis/objective.py, refnx/analysis/parameter.py, refnx/analysis/test/test_curvefitter.py, refnx/reflect/_code_fragment.py, refnx/reflect/structure.py
- Improves plotting from the script exported from the pyqt gui.
- This also required the parameter generator from the sampled chain to be modified
- fixed a bug when initialising sampler from a chain, if the sampler hadn't been run before.
=> MAINT: improve fragment plotting

refnx/reflect/_reflect.py, refnx/reflect/test/test_reflect.py, src/MyComplex.h, src/_creflect.pyx, src/refcalc.cpp
@mdoucet has created a repo comparing refl1d and refnx output for some corner cases. This PR checks the C + py abeles calc are the same in refnx for that corner case.
This PR also moves from the MyComplex class to the C++ implementation (less things to go wrong).
=> TST: compare c+py ref calc

refnx/reflect/_code_fragment.py
@igresh, you might like this one.
=> ENH: add MPI option for MCMC analysis script exported from GUI.

refnx/reflect/test/test_reflect.py
Checks that parallel evaluation of a (ReflectModel) objective works correctly. This check is useful because parallel evaluation could fail at a higher level than this (in emcee or scipy.optimize.differential_evolution), and this would signify whether the problem is at this level or higher.
=> TST: parallel evaluation of Objective

refnx/reflect/_interactive_modeller.py
=> MAINT: interactive modeller respects Transform closes #gh309

refnx/reflect/_app/view.py
print iterations in fit progress
inject best fit so far into objective when fit is aborted.
=> MAINT: GUI, recover from fit abort

refnx/analysis/curvefitter.py, refnx/analysis/objective.py
A possible (pragmatic) solution to https://github.com/refnx/refnx/issues/318
=> A solution to minimise the nlpost

.travis.yml, CHANGELOG.txt, refnx/reduce/rebin.py, refnx/reduce/test/test_rebin.py
Rebinning procedure had bug (not relevant to data analysis code).
=> BUG: rebinning procedure closes #344

CHANGELOG.txt, refnx/reflect/__init__.py, refnx/reflect/interface.py, refnx/reflect/structure.py, refnx/reflect/test/test_interface.py, refnx/reflect/test/test_spline.py, refnx/reflect/test/test_structure.py
Adds different function forms for the interfacial profiles between components.
=> ENH: add different Interfacial roughness profiles (WIP)

refnx/reflect/reflect_model.py
`InterpolatedUnivariateSpline` is about 10% slower than `splrep` + `splev`
=> MAINT: splev and splrep for convolution

CHANGELOG.txt, refnx/reflect/_reflect.py, refnx/reflect/structure.py, refnx/reflect/test/test_structure.py, src/_creflect.pyx
This will provide huge timesavings for reflectivity calculations of microsliced profiles.
=> ENH: cythonize contract_by_area

CHANGELOG.txt, refnx/util/__init__.py, refnx/util/general.py, refnx/util/test/test_general.py
Adds a neutron transmission calculator based on the periodictable package.
=> ENH: neutron transmission calculator

refnx/_lib/emcee/__init__.py, refnx/_lib/emcee/autocorr.py, refnx/_lib/emcee/ensemble.py, refnx/_lib/emcee/moves/de.py, refnx/_lib/emcee/moves/mh.py, refnx/_lib/emcee/moves/red_blue.py, refnx/_lib/emcee/pbar.py
Update the vendored emcee code.
=> MAINT: emcee vendor update

CHANGELOG.txt, refnx/reduce/event.py, refnx/reduce/test/test_event.py, src/_cevent2.pyx
The event file reader will now read any ANSTO packedbin format.
=> Universal event file reader

refnx/reflect/_lipid.py, refnx/reflect/structure.py
Sync docstring for the class and the __init__ method.
=> DOC: LipidLeaflet update docstring

.travis.yml
=> CI: brew update

refnx/reflect/structure.py, refnx/reflect/test/test_structure.py
Changing the inheritance hierarchy to something that's more rational.
=> MAINT: SLD/MaterialSLD class reorg

refnx/reflect/structure.py, refnx/reflect/test/test_structure.py
```
Ni = SLD(8)
layer = Ni(120, 3)
s = layer * 5
assert len(s) == 5
```
=> Multiply components to get them to repeat

refnx/analysis/objective.py
=> MAINT: use np.dot in chisqr calc

CHANGELOG.txt, examples/reflectometry_analysis.ipynb, refnx/analysis/curvefitter.py, refnx/analysis/test/test_curvefitter.py
closes #422 
@jfkcooper, it turns out it wasn't so hard.
=> ENH: add progress bar for fitting

.github/workflows/pythonpackage.yml, CHANGELOG.txt
Try using github actions to test on macOS
=> CI: try macOS build matrix on github actions

build_manylinux_wheels.sh, setup.py
A bugfix release because of the Linux wheels.
=> REL v0.1.14

refnx/analysis/bounds.py
Don't try to pickle stats distributions, that's sloooooow.
=> PERF: fix regression from c3157e

CHANGELOG.txt, refnx/reduce/__init__.py, refnx/reduce/batch_reduce/reduction_template.ipynb, refnx/reduce/batchreduction.py, refnx/reduce/platypusnexus.py, refnx/reduce/reduce.py, refnx/reduce/test/test_reduce.py
`ReduceNexus`, `ReflectNexus`, `reduce_stitch` functions can now use a `ReductionOptions` dict to specify various processing options. The changes to `reduce_stitch` (also BatchReducer) means different angles can use different processing options.
=> MAINT: ReductionOptions

CHANGELOG.txt, refnx/reduce/__init__.py, refnx/reduce/_auto_reduction.py, refnx/reduce/reduce.py
Auto-reduction of Platypus/Spatz datafiles.
=> ENH: AutoReducer

appveyor.yml
Auto-reduction of Platypus/Spatz datafiles.
=> CI: update appveyor miniconda

refnx/analysis/objective.py, refnx/reflect/_app/view.py
Removes a deprecation warning in mpl 3.3
=> MAINT: fix DeprecationWarnings

doc/index.rst, doc/model_selection.ipynb
Add a short notebook showing model selection with dynesty
=> DOC: model selection

.github/workflows/pythonpackage.yml
Move to v2 of various actions.
=> CI: move to actions v2

refnx/reduce/platypusnexus.py, refnx/reduce/test/test_platypusnexus.py
Have applied your suggestions, cut out the analyser params but have kept the flipper params. They're not needed for reduction but are still useful I think.
=> PNR Catalogue

CHANGELOG.txt, refnx/reduce/batchreduction.py
Add batch reduction for Spatz.
=> ENH: SPZ batch reduction

experimental/jax_abeles.ipynb, refnx/reflect/_jax_reflect.py, refnx/reflect/reflect_model.py
This JAX backend is very slow at the moment. I think this is because XLA is trying to unroll the for loop which is plain crazy if you don't know how many layers there are.
=> ENH: add jax_abeles

CHANGELOG.txt, refnx/reflect/spline.py
=> MAINT: Spline, make dz.bounds.lb > 0

refnx/_lib/emcee/backends/backend.py, refnx/_lib/emcee/backends/hdf.py, refnx/_lib/emcee/ensemble.py
=> MAINT: update emcee vendored

CHANGELOG.txt, refnx/dataset/data1d.py, refnx/reduce/reduce.py, refnx/reduce/test/test_reduce.py
@llimeht, this is some of what you wanted to see. Don't rely on the header remaining the same. As ORSO progresses it'll go toward that kind of format.
=> ENH: add a header to reduced datafiles.

CHANGELOG.txt, refnx/analysis/parameter.py, refnx/reflect/_app/treeview_gui_model.py, refnx/reflect/_app/ui/motofit.ui, refnx/reflect/_app/view.py, refnx/reflect/_lipid.py, refnx/reflect/reflect_model.py, refnx/reflect/spline.py, refnx/reflect/structure.py
=> ENH: add units str to Parameter

refnx/reduce/__init__.py, refnx/reduce/platypusnexus.py, refnx/reduce/reduce.py, refnx/reduce/test/test_platypusnexus.py, refnx/reduce/test/test_reduce.py, refnx/util/general.py, refnx/util/quickplot.py
Polarised correction and reduction for a single angle working as expected.
- Have vectorised matrix calculations
- Included PolarisationEfficiency class (to be expanded upon)
- Added tests for PolarisedReduce and PolarisationEfficiency
Still to do:
- Finish uncertainty propagation in matrix calculations
- Add more PolarisationEfficiency set-ups based on literature
=> Polarised reduce class

CHANGELOG.txt, refnx/analysis/objective.py, refnx/analysis/parameter.py, refnx/analysis/test/test_curvefitter.py, refnx/analysis/test/test_objective.py, refnx/analysis/test/test_parameter.py
@dcortie. This PR will be useful for Magnetic PNR.
```
n = Parameter(6, name="nuclear SLD", vary=True, bounds=(5, 8))
m = Parameter(3, name="magnetic SLD", vary=True, bounds=(0, 3)
FeUU = SLD(0.0)
FeDD = SLD(0.0)
FeUU.constraint = n + m
FeUU.constraint = n - m
```
=> ENH: introduce auxiliary_params

.github/workflows/build_wheels.yml, .github/workflows/pythonpackage.yml, CHANGELOG.txt, pyproject.toml, setup.cfg, setup.py, tools/build_manylinux_wheels.sh
Hopefully this doesn't cause issues down the line. Moving lots of config from setup.py to setup.cfg.
=> BLD: expand setup.cfg

.github/workflows/pythonpackage.yml, tools/app/check_app_starts.py
This might turn out to be flaky, but we'll see.
=> Checks whether the pyinstaller created executable starts under macOS

CHANGELOG.txt, refnx/reflect/_app/view.py, refnx/reflect/_lipid.py, refnx/reflect/spline.py, refnx/reflect/structure.py, refnx/reflect/test/test_spline.py, refnx/reflect/test/test_structure.py
@igresh @haydenrob a little energy dispersive machinery. Existing refnx code should 'just work'. However, refellips is going to have to be adjusted to work with the changes here.
`Component` that use Scatterers have to be rewritten slightly, to use `Scatterer.complex(getattr(structure, "wavelength", None))` when trying to calculate complex SLD/RI.
=> A little energy dispersive machinery

setup.py
Creating a new release to update pyproject.toml
=> REL v0.1.28

CHANGELOG.txt, refnx/analysis/objective.py, refnx/analysis/test/test_globalfitting.py
=> ENH: Lagrangian multipliers

CHANGELOG.txt, pyproject.toml, refnx/reflect/reflect_model.py, refnx/reflect/test/test_reflect.py, src/_cyreflect.pyx, src/refcalc.c
(probably don't use cython backends they seem to be a lot slower, just including for completeness)
=> cython_parratt implementation

refnx/reduce/test/test_event.py, src/_cevent.pyx
=> MAINT: add SPZ event mode reader

CHANGELOG.txt, refnx/reduce/platypusnexus.py, refnx/reduce/test/test_platypusnexus.py
=> ENH: only return requested keys from catalogue

CHANGELOG.txt, refnx/reduce/reduce.py, refnx/reduce/test/test_batch_reduce.py, refnx/reduce/test/test_reduce.py
Fixes an issue found by Anton.
=> BUG: fix data_folder concatentation issue in reduce_stitch

refnx/reduce/reduce.py
=> MAINT: use np.savez for saving offspec

refnx/reduce/platypusnexus.py
This is a draft PR for a function to plot an 2D contour map of an off-specular pattern. 
I am unsure where this function "belongs" in the code, so have put in platypusnexus.py for now. Better suggestions?
=> A prototype of the off-specular plotter

refnx/reduce/platypusnexus.py
line 779, add raise so warning is output correctly
=> MAINT: fix spinset raise warning

CHANGELOG.txt, refnx/reflect/_lipid.py, refnx/reflect/tests/test__lipid.py
to allow guest molecules in head region
=> MAINT: changed parameterisation of LipidLeafletGuest
